version: '3'

services:
  db:
    restart: always
    image: mysql:5.7
    environment:
    - MYSQL_DATABASE='employee_db'
    - MYSQL_USER='root'
    - MYSQL_PASSWORD='password'
    - MYSQL_ROOT_PASSWORD='password'
    volumes:
    - /var/lib/mysql
    ports:
    - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code/
    ports:
      - "8000:8000"
    depends_on: 
      - db
   